name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
          # Use our own cache, obviously.
          cache: false
      - name: Install gobuildcache
        run: go install github.com/richardartoul/gobuildcache@latest
      - name: Run short tests
        env:
          BACKEND_TYPE: s3
          S3_BUCKET: EXAMPLE_BUCKET
          S3_PREFIX: EXAMPLE_PREFIX
          AWS_REGION: EXAMPLE_REGION
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GOCACHEPROG: gobuildcache
        run: go test ./...


